/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "alexander-nevsky": {
    "base": "alexander-nevsky",
    "width": 1920,
    "height": 1816,
    "fallbackWidth": 800,
    "fallbackHeight": 757,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "city-walls": {
    "base": "city-walls",
    "width": 800,
    "height": 1067,
    "fallbackWidth": 800,
    "fallbackHeight": 1067,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coast": {
    "base": "coast",
    "width": 1600,
    "height": 1200,
    "fallbackWidth": 1600,
    "fallbackHeight": 1200,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coastal": {
    "base": "coastal",
    "width": 1600,
    "height": 1200,
    "fallbackWidth": 1600,
    "fallbackHeight": 1200,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "compare": {
    "base": "compare",
    "width": 1920,
    "height": 1816,
    "fallbackWidth": 1920,
    "fallbackHeight": 1816,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 1920,
    "height": 1440,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "family": {
    "base": "family",
    "width": 1920,
    "height": 1080,
    "fallbackWidth": 800,
    "fallbackHeight": 450,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 1920,
    "height": 742,
    "fallbackWidth": 800,
    "fallbackHeight": 309,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food-and-wine": {
    "base": "food-and-wine",
    "width": 1920,
    "height": 742,
    "fallbackWidth": 800,
    "fallbackHeight": 309,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero": {
    "base": "hero",
    "width": 1400,
    "height": 2020,
    "fallbackWidth": 1400,
    "fallbackHeight": 2020,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 1400,
    "height": 2020,
    "fallbackWidth": 1400,
    "fallbackHeight": 2020,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "historic": {
    "base": "historic",
    "width": 1920,
    "height": 930,
    "fallbackWidth": 800,
    "fallbackHeight": 388,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "kadriorg": {
    "base": "kadriorg",
    "width": 1920,
    "height": 1080,
    "fallbackWidth": 800,
    "fallbackHeight": 450,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "lahemaa": {
    "base": "lahemaa",
    "width": 1920,
    "height": 998,
    "fallbackWidth": 800,
    "fallbackHeight": 416,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "market-square": {
    "base": "market-square",
    "width": 1920,
    "height": 930,
    "fallbackWidth": 800,
    "fallbackHeight": 388,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "nature": {
    "base": "nature",
    "width": 1920,
    "height": 998,
    "fallbackWidth": 1920,
    "fallbackHeight": 998,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 1920,
    "height": 930,
    "fallbackWidth": 1920,
    "fallbackHeight": 930,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "photography": {
    "base": "photography",
    "width": 1400,
    "height": 2020,
    "fallbackWidth": 1400,
    "fallbackHeight": 2020,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "private": {
    "base": "private",
    "width": 1920,
    "height": 1080,
    "fallbackWidth": 800,
    "fallbackHeight": 450,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "tallinn-old-town": {
    "base": "tallinn-old-town",
    "width": 1920,
    "height": 930,
    "fallbackWidth": 800,
    "fallbackHeight": 388,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "toompea": {
    "base": "toompea",
    "width": 800,
    "height": 600,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "viewpoints": {
    "base": "viewpoints",
    "width": 800,
    "height": 1154,
    "fallbackWidth": 800,
    "fallbackHeight": 1154,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "walking": {
    "base": "walking",
    "width": 800,
    "height": 1154,
    "fallbackWidth": 800,
    "fallbackHeight": 1154,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "wine": {
    "base": "wine",
    "width": 1920,
    "height": 742,
    "fallbackWidth": 800,
    "fallbackHeight": 309,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
